name: ode-artwork-downloader
version: git
summary: ODE Artwork Downloader
description: |
  Download artwork for ODE (Optical Disc Emulator) devices.
  
  This application helps you find and download artwork for your optical disc
  emulator, supporting various disc formats and artwork sources.

base: core22
confinement: strict
grade: stable
icon: assets/icons/icon.png

apps:
  ode-artwork-downloader:
    command: bin/ode-artwork-downloader
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - opengl

parts:
  ode-artwork-downloader:
    plugin: dump
    source: snap/local
    stage-packages:
      - libgtk-3-0
      - libssl3
    organize:
      bin/ode-artwork-downloader: bin/ode-artwork-downloader
