name: ode-artwork-downloader
version: git
summary: ODE Artwork Downloader
description: |
  Download artwork for ODE (Optical Disc Emulator) devices.
  
  This application helps you find and download artwork for your optical disc
  emulator, supporting various disc formats and artwork sources.

base: core22
confinement: strict
grade: stable
icon: assets/icons/icon.png

apps:
  ode-artwork-downloader:
    command: bin/ode-artwork-downloader
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  ode-artwork-downloader:
    plugin: nil
    source: .
    build-packages:
      - libgtk-3-dev
      - libssl-dev
      - pkg-config
      - curl
      - gcc
      - git
      - libc6-dev
    stage-packages:
      - libgtk-3-0
      - libssl3
    override-build: |
      # Check if cargo/rustup is already available (self-hosted runner)
      if [ -d "$HOME/.cargo/bin" ] && [ -f "$HOME/.cargo/bin/cargo" ]; then
        echo "Using pre-installed rustup from ~/.cargo/bin"
        export PATH="$HOME/.cargo/bin:$PATH"
      else
        # GitHub-hosted containerized build - install rustup
        echo "Installing rustup for containerized build"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        export PATH="$HOME/.cargo/bin:$PATH"
        source "$HOME/.cargo/env"
      fi
      
      cargo build --release
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp target/release/ode-artwork-downloader $CRAFT_PART_INSTALL/bin/
